### ISSUE TITLE
34700 -> 34740 breaks pcsc-lite / pcscd and subsequently yubikey with gpg

### ISSUE THREAD

**Issue by xlfe** [clearlinux/distribution#2376]
34740
```
gpg2 --card-status
```
Shows no cards connected.

Additionally
```
systemctl status pcscd
```
Was disabled. Once enabled, I was getting the following error
```
pcscd[27049]: 00000000 ccid_usb.c:858:WriteUSB() write failed (3/6): -4 LIBUSB_ERROR_NO_DEVICE
```

Once reverting back to 34700, gpg2 --card-status works again (With my Yubikey) and I get
```
● pcscd.service - PC/SC Smart Card Daemon
     Loaded: loaded (/usr/lib/systemd/system/pcscd.service; indirect; vendor preset: disabled)
     Active: active (running) since Wed 2021-06-16 13:41:22 AEST; 15s ago
TriggeredBy: ● pcscd.socket
       Docs: man:pcscd(8)
   Main PID: 2247 (pcscd)
      Tasks: 6 (limit: 18648)
     Memory: 1.2M
     CGroup: /system.slice/pcscd.service
             └─2247 /usr/bin/pcscd --foreground --auto-exit

Jun 16 13:41:22 pmic systemd[1]: Started PC/SC Smart Card Daemon.
```

And no errors about LIBUSB_ERROR_NO_DEVICE

**Comment by mdhorn** [comment]
@phmccarty Found that we should stay on the 2.2.x release of gnupg.
Downgrading to the latest 2.2.28 for the next build this week.

**Comment by mdhorn** [comment]
@phmccarty Good find on the bug fix patch for 2.2.28 🥇 👍🏽

**Comment by phmccarty** [comment]
Since I didn't comment about the patch in the commit message, this is the stable branch patch I backported to fix the build in 2.2.28:

https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=commitdiff;h=c8b2162c0e7eb42b74811b7ed225fa0f56be4083

(We don't pass `--disable-ldap` to `./configure`, but LDAP support is not properly detected, so the end result is the same.)

**Comment by phmccarty** [comment]
gnupg was downgraded to the 2.2 series in release 34760.

@xlfe Let us know if that fixes the issue.

**Comment by xlfe** [comment]
@phmccarty just upgraded to 34760 and yubikey functioning as expected again.

tested with ssh and gpg and works.

One thing - I still see the following

```
systemctl status pcscd
Password: 
● pcscd.service - PC/SC Smart Card Daemon
     Loaded: loaded (/usr/lib/systemd/system/pcscd.service; indirect; vendor preset: disabled)
     Active: inactive (dead)
TriggeredBy: ● pcscd.socket
       Docs: man:pcscd(8)
```

But obviously that doesn't matter because its all working.

thanks for the fix!
