### ISSUE TITLE
29890: networking in Kubernetes broken

### ISSUE THREAD

**Issue by pohly** [clearlinux/distribution#904]
We are bringing up a Kubernetes cluster using runc ("make start" in PMEM-CSI). Starting with Clear Linux 29890, connecting to a service provided by a pod running on a different node via TCP fails ("connection refused"). It works in 29880.

The same situation with CRI-O as runtime (broken in 29890, works in 29880).

29890 updated both runc and CRI-O.

This issue obviously doesn't have enough information to reproduce. I'm filing it as a placeholder. If you don't see any issues in your own testing, we need to dig deeper. I already tried with cloud-native-setup, but that failed completely for me (https://github.com/clearlinux/cloud-native-setup/issues/101).

**Comment by hnanni** [comment]
Hello @pohly

We did not publish (as release version) 29890, but yes that version got the runc and cri-o update.
The k8s' tests used for QA, are based on the cloud-native-setup scripts (although they do not depend on vagrant/libvirt to launch VMs). From 29920 to 29940, the tests have been running successfully.

I will synchronize with you to
1 (If this is the case) keep your tests using the staging version, but have your them to consider the current release criteria tests
2. Extend the release criteria, with the tests you have as much as posible/meaningful

**Comment by pohly** [comment]
Here's a way to reproduce the issue.
```
cat >service.yaml <<EOF
apiVersion: v1
kind: Service
metadata:
  name: socat-service
spec:
  ports:
  - port: 10000
  selector:
    app: socat
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: socat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socat
  serviceName: socat-service
  template:
    metadata:
      labels:
        app: socat
    spec:
      containers:
      - args:
        - tcp-listen:10000,fork,reuseaddr
        - stdio
        image: alpine/socat:1.0.3
        name: socat
EOF

cat >client.yaml <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: socat-client
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - socat
        topologyKey: "kubernetes.io/hostname"
  containers:
    - command:
      - /bin/sh
      - "-c"
      - "echo 'hello world' | socat stdin tcp:$(SOCAT_SERVICE_PORT_10000_TCP_ADDR):$(SOCAT_SERVICE_PORT_10000_TCP_PORT) 2>/dev/termination-log"
      image: alpine/socat:1.0.3
      name: socat
EOF

kubectl create -f service.yaml
# wait until pod "socat" is running
kubectl create -f client.yaml
```

Expected result:
- pods on different nodes:
```
kubectl get pods -o wide
socat-0                       1/1     Running            0          20m     10.244.2.2    pmem-csi-clear-29880-crio-worker2   <none>           <none>
socat-client                  0/1     CrashLoopBackOff   5          3m40s   10.244.3.4    pmem-csi-clear-29880-crio-worker3   <none>           <none>
```

- socat-client keeps terminating without error and gets restarted:
```
kubectl describe pods/socat-client
...
Containers:
  socat:
    Container ID:  cri-o://f10447d7d99ad7a2d3f225200a75cf025d09d9db6471781ccc8c9caaefcea6e7
    Image:         alpine/socat:1.0.3
    Image ID:      docker.io/alpine/socat@sha256:e996738d3921a844b3809a431f710104d467f448f3f4023fc14fc19f566b48e2
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      echo 'hello world' | socat stdin tcp:$(SOCAT_SERVICE_PORT_10000_TCP_ADDR):$(SOCAT_SERVICE_PORT_10000_TCP_PORT) 2>/dev/termination-log
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 17 Jun 2019 22:35:06 +0200
      Finished:     Mon, 17 Jun 2019 22:35:06 +0200
    Ready:          False
    Restart Count:  5
    Environment:    <none>
```

- socat logs "hello world":
```
kubectl logs socat-0
hello world
hello world
hello world
....
```

This was with 29880 and CRI-O.

Actual result with 29890 (because that was the first version where it broke) and CRI-O:

- socat client hangs:
```
kubectl describe pods/socat-client
...
Containers:
  socat:
    Container ID:  cri-o://2ca51acb69dd164e5dee34a7ebe70b7eecac08fb4ea9f288682eac999e24cb1f
    Image:         alpine/socat:1.0.3
    Image ID:      docker.io/alpine/socat@sha256:e996738d3921a844b3809a431f710104d467f448f3f4023fc14fc19f566b48e2
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      echo 'hello world' | socat stdin tcp:$(SOCAT_SERVICE_PORT_10000_TCP_ADDR):$(SOCAT_SERVICE_PORT_10000_TCP_PORT) 2>/dev/termination-log
    State:          Running
      Started:      Mon, 17 Jun 2019 22:40:10 +0200
...
```

I expect socat to time out eventually, but that seems to take a while (several minutes now and still running) and I don't want to wait for it...
